#
# GitHub Action manifest for PSRule
#
name: 'PSRule'
description: 'Run rules in a GitHub repository.'
author: 'Microsoft'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  includePath:
    description: 'An path containing rules to use for analysis.'
    default: '.ps-rule/'
    required: false

  inputPath:
    description: 'The path PSRule will look for files to validate.'
    default: '.'
    required: false

  modules:
    description: 'A comma separated list of modules to use for analysis.'
    default: ''
    required: false

  baseline:
    description: 'The name of a PSRule baseline to use.'
    default: ''
    required: false

  conventions:
    description: 'A comma separated list of conventions to use.'
    default: ''
    required: false

  option:
    description: 'The path to an options file.'
    default: ''
    required: false

  outcome:
    description: 'Filters output to include results with the specified outcome.'
    default: 'Processed'
    required: false

  outputFormat:
    description: 'The format to use when writing results to disk. When set to None results are not written to disk.'
    default: 'None'
    required: false

  outputPath:
    description: 'The file path to write results to.'
    default: ''
    required: false

  path:
    description: 'The working directory PSRule is run from.'
    default: ''
    required: false

  prerelease:
    description: 'Determine if a pre-release module version is installed.'
    default: 'false'
    required: false

  repository:
    description: 'The name of the PowerShell repository where PSRule modules are installed from. By default this is the PowerShell Gallery.'
    default: 'PSGallery'
    required: false

  summary:
    description: 'Determines if a job summary is written.'
    default: 'true'
    required: false

  version:
    description: 'The specific version of PSRule to use.'
    default: ''
    required: false

  restore:
    description: 'Restore PSRule modules.'
    default: 'true'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Check .NET version
      shell: pwsh
      run: dotnet --version

    - name: Install PSRule
      shell: pwsh
      run: dotnet tool restore --tool-manifest $Env:GITHUB_ACTION_PATH/.config/dotnet-tools.json

    - name: Run PSRule
      shell: pwsh
      working-directory: ${{ github.workspace }}
      run: |-
        #${{ github.action_path }}/bootstrap.ps1 -InputType '${{ inputs.inputType }}' -InputPath '${{ inputs.inputPath }}' -Modules '${{ inputs.modules }}' -Source '${{ inputs.source }}' -Baseline '${{ inputs.baseline }}' -Conventions '${{ inputs.conventions }}' -Option '${{ inputs.option }}' -Outcome '${{ inputs.outcome }}' -OutputFormat '${{ inputs.outputFormat }}' -OutputPath '${{ inputs.outputPath }}' -Path '${{ inputs.path }}' -PreRelease '${{ inputs.prerelease }}' -Repository '${{ inputs.repository }}' -Summary '${{ inputs.summary }}' -Version '${{ inputs.version }}'
        dotnet tool run ps-rule run --in-github-actions
